CREATE TABLE stats (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  userid INTEGER REFERENCES accounts(id) ON DELETE CASCADE,
  wins INTEGER,
  wars_won INTEGER,
  wars_lost INTEGER,
  games_played INTEGER,
  longest_game INTEGER,
  date_modified TIMESTAMPTZ DEFAULT now() NOT NULL
);